version: "0.1"

services:
  blog_app:
    container_name: blog_app
    restart: unless-stopped
    image: aasimkhan/jekyll-theme-so-simple
    build:
      context: ./app
      dockerfile: ops/Dockerfile
    ports:
      - "4000:4000"
    command: bash -c "bundle && bundle exec jekyll build -d ./_build && bundle exec jekyll serve --host 0.0.0.0"
    volumes:
      - ./app:/app
