name: Upload to S3

on: [push, pull_request]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: test
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          description: 'Preview app'
          environment: preview

      - uses: shallwefootball/upload-s3-action@v1.3.0
        name: Upload to S3
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: '../app/_site/'

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_url: https://aws-bucket.s3.eu-west-2.amazonaws.com/${{ steps.S3.outputs.object_key }}/index.html
          state: 'success'
          deployment_id: ${{ steps.test.outputs.deployment_id }}
