name: Upload to S3

on: [push, pull_request]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Upload to S3
      - uses: hkusu/s3-upload-action@v2
        id: upload # specify some ID for use in subsequent steps
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-west-2'
          aws-bucket: ${{ secrets.AWS_BUCKET }}
          file-path: './app/_site/*'
          output-qr-url: 'true' # specify true
          public: 'true'
      - name: Show URL
        run: echo '${{ steps.upload.outputs.qr-url }}' # use this output
